version: '3.8'

services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mark007!
      POSTGRES_DB: users
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - database
    environment:
      ConnectionStrings__PostgresConnection: "Host=database;Port=5432;Database=users;Username=postgres;Password=mark007!"
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
